[general]
import = [
    "~/.config/alacritty/themes/gruvbox-dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 4, y = 0 }
startup_mode = "Fullscreen"
opacity = 0.9

[font]
normal = { family = "Iosevka Nerd Font Mono", style = "Medium" }
bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Medium Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }
size = 9

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Block", blinking = "On" }

